name: TorchLight
main: org.xdxa.torchlight.TorchLight
version: ${version}
commands:
   torch:
      description: Toggles plugin
      usage: /<command>

permissions:
  torchlight.allow:
    description: Allows use of the plugin
    default: true
  torchlight.command:
    description: Allows use of the /torch command
    default: true
  torchlight.enabled:
    description: Defaults the player to enabled
    default: true